# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a8203860af811b947ec6c228f7af6f27cc819128ac792d958a7610f1af0600355e3f42ea5a0250cda255ffb6cf197234f57cd092d15c0d4c345d3479dac3f68

test:
  secret_key_base: 49a65c1c63256b718e1e811a3a30d3f24a0f3c5b650aec24096f94681d6b4bbfd4466f920e5f40e0fa554fa97ead2d536c4c1a0299f45988a50536d0480f6b8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
